name: illustriousworld
favicon: null
layout_spectrum: 0.5890072851907462
typography_spectrum: 0.8537926014978439
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9ddaf7'
    - '#010101'
    - '#ee504e'
    - '#276eb5'
  brandStrength: 0.5
  lightness: 0.36628350452519953
  saturation: 0.8839096981100738
  rhythmicContrast: 0.7433689686004072
purpose: []
